### ISSUE TITLE
Make changes in OCI platform

### ISSUE THREAD

**Issue by shreyaagrawal0809** [CivicDataLab/assam-tenders-data#22]
- [x] Filters are not active/working
- [x] Sort is not working - need to reach out to @Abhi2102 
- [x] When downloading individual contract data few of the entries of ckan is also coming
- [x] Downloading the whole or selected page contracts are giving old json/xlsx
- [x] Truncating overflowing tender titles

**Comment by sphanidatta** [comment]
Contracts Data Page 
- [ ] Contracts Value, decimal issue (check if front end / backend)
- [ ] Fiscal Year bug for 2015-16, 2023-24
- [ ] Tender value, high number of NA tender values 
- [ ] Filtered Data Download JSONs -  allows all tenders or just the current pagenation but not the all tenders identified under the filter 
- [ ] [Update Publication Policy 
](https://docs.google.com/document/d/15he0_XkduZwSA-iQdpTrp5gZwOj-YP8Hulf4GJt06Kk/edit#heading=h.bzm32h7uocaq)

Data [Shreya to reach out to Andrii for this]
- [ ] Only gives 21k Tenders data, not all 45k tenders (need to change) 
- [ ] frequency of updating data (and status update) - pipeline to be set in place
- [ ] The format of flattened data needs rethinking

Data Analysis
- [ ]  Need to check calculations (depends on tender and contract value issues stated above)
- [ ] Filter in charts don't allow to check 2023-24
